import { RankedProfile } from "../types/index.js";

export const MOCK_PROFILES: RankedProfile[] = [
  {
    id: "mock-001",
    source: "psychology_today",
    name: "Dr. Sarah Chen",
    credentials: "PhD, LCSW",
    specialties: ["anxiety", "depression", "stress", "life transitions"],
    insuranceAccepted: ["Aetna", "Blue Cross", "Cigna", "United Healthcare"],
    location: "San Francisco, CA",
    telehealth: true,
    acceptingNewPatients: true,
    nextAvailableSlot: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString(),
    bookingUrl: "https://www.psychologytoday.com/us/therapists/sarah-chen",
    profileUrl: "https://www.psychologytoday.com/us/therapists/sarah-chen",
    photoUrl: undefined,
    score: 110,
    tradeoffExplanation:
      "A strong match — she specializes in anxiety and accepts your insurance. Next opening is in 3 days, and she offers telehealth if that's more convenient.",
  },
  {
    id: "mock-002",
    source: "zocdoc",
    name: "Marcus Williams",
    credentials: "LMFT",
    specialties: ["anxiety", "trauma", "couples", "relationship issues"],
    insuranceAccepted: ["Cigna", "Kaiser", "Magellan"],
    selfPayRate: "$150",
    location: "San Francisco, CA",
    telehealth: true,
    acceptingNewPatients: true,
    nextAvailableSlot: new Date(Date.now() + 1 * 24 * 60 * 60 * 1000).toISOString(),
    bookingUrl: "https://www.zocdoc.com/doctor/marcus-williams",
    profileUrl: "https://www.zocdoc.com/doctor/marcus-williams",
    score: 95,
    tradeoffExplanation:
      "Earliest availability — tomorrow — and specializes in both anxiety and trauma. Tradeoff: your insurance isn't listed, but the $150 self-pay rate is reasonable.",
  },
  {
    id: "mock-003",
    source: "psychology_today",
    name: "Dr. Priya Nair",
    credentials: "PsyD",
    specialties: ["depression", "anxiety", "grief", "women's issues"],
    insuranceAccepted: ["Aetna", "Blue Cross", "Blue Shield", "Oscar"],
    location: "Oakland, CA",
    telehealth: true,
    acceptingNewPatients: true,
    nextAvailableSlot: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString(),
    bookingUrl: "https://www.psychologytoday.com/us/therapists/priya-nair",
    profileUrl: "https://www.psychologytoday.com/us/therapists/priya-nair",
    score: 85,
    tradeoffExplanation:
      "Accepts your insurance and brings a warm, strengths-based approach. She's based in Oakland but offers telehealth. First slot is about a week out.",
  },
  {
    id: "mock-004",
    source: "therapy_den",
    name: "Jordan Lee",
    credentials: "LPC",
    specialties: ["anxiety", "lgbtq+", "identity", "young adults"],
    insuranceAccepted: [],
    selfPayRate: "$120",
    location: "San Francisco, CA",
    telehealth: true,
    acceptingNewPatients: true,
    nextAvailableSlot: new Date(Date.now() + 4 * 24 * 60 * 60 * 1000).toISOString(),
    contactEmail: "jordan@jordanleetherapy.com",
    profileUrl: "https://therapyden.com/therapist/jordan-lee",
    score: 70,
    tradeoffExplanation:
      "Specializes in anxiety with an affirming, identity-focused approach. Self-pay only at $120/session — no insurance accepted — but offers a sliding scale.",
  },
  {
    id: "mock-005",
    source: "psychology_today",
    name: "Dr. Elena Russo",
    credentials: "PhD",
    specialties: ["anxiety", "ocd", "cbt", "phobias"],
    insuranceAccepted: ["Aetna", "United Healthcare", "Optum"],
    location: "San Jose, CA",
    telehealth: false,
    acceptingNewPatients: true,
    nextAvailableSlot: new Date(Date.now() + 10 * 24 * 60 * 60 * 1000).toISOString(),
    bookingUrl: "https://www.psychologytoday.com/us/therapists/elena-russo",
    profileUrl: "https://www.psychologytoday.com/us/therapists/elena-russo",
    score: 60,
    tradeoffExplanation:
      "A CBT specialist with strong expertise in OCD and anxiety. Tradeoff: in-person only (San Jose) and the next slot is 10 days out.",
  },
];
